// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOmj2GrVbuFryb0HfrYA8JGW1fint4IrY',
    appId: '1:969371165439:web:7330cabf82fcc030c162ca',
    messagingSenderId: '969371165439',
    projectId: 'unimas-foodhub',
    authDomain: 'unimas-foodhub.firebaseapp.com',
    databaseURL: 'https://unimas-foodhub-default-rtdb.firebaseio.com',
    storageBucket: 'unimas-foodhub.firebasestorage.app',
    measurementId: 'G-TJZY7KZQ28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQHDVrFtwLu6huoCXgZQYxpjbZTkK9D4',
    appId: '1:969371165439:android:cd8d99c174ec66a5c162ca',
    messagingSenderId: '969371165439',
    projectId: 'unimas-foodhub',
    databaseURL: 'https://unimas-foodhub-default-rtdb.firebaseio.com',
    storageBucket: 'unimas-foodhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3S_t0yPOz_1RAjLscrmjjzjRVz0febi4',
    appId: '1:969371165439:ios:a5ab85f6fac376f9c162ca',
    messagingSenderId: '969371165439',
    projectId: 'unimas-foodhub',
    databaseURL: 'https://unimas-foodhub-default-rtdb.firebaseio.com',
    storageBucket: 'unimas-foodhub.firebasestorage.app',
    iosBundleId: 'com.example.unimasFoodhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3S_t0yPOz_1RAjLscrmjjzjRVz0febi4',
    appId: '1:969371165439:ios:a5ab85f6fac376f9c162ca',
    messagingSenderId: '969371165439',
    projectId: 'unimas-foodhub',
    databaseURL: 'https://unimas-foodhub-default-rtdb.firebaseio.com',
    storageBucket: 'unimas-foodhub.firebasestorage.app',
    iosBundleId: 'com.example.unimasFoodhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOmj2GrVbuFryb0HfrYA8JGW1fint4IrY',
    appId: '1:969371165439:web:f6fbfc8a85f2ff8ac162ca',
    messagingSenderId: '969371165439',
    projectId: 'unimas-foodhub',
    authDomain: 'unimas-foodhub.firebaseapp.com',
    databaseURL: 'https://unimas-foodhub-default-rtdb.firebaseio.com',
    storageBucket: 'unimas-foodhub.firebasestorage.app',
    measurementId: 'G-75MDWZX0JJ',
  );
}
